### ISSUE TITLE
Explore how we could show app version and build related information

### ISSUE THREAD

**Issue by shashwatbangar** [hotwax/ionic-sdk#68]
Explore and identify practices followed to gather and displaying app version, and build date time time related information

**Comment by shashwatbangar** [comment]
Referred to following link to show app version 
https://medium.com/hceverything/how-to-show-your-app-version-from-package-json-in-your-vue-application-11e882b97d8c

How we do it:
1. First we define a global variable in vue.config.js using webpack's definePlugin method.
2. We will define this variable in environment file.
3. We can name it anything following environment variable convention
4. Now it's in our app. To use to across the app store it in a state or somewhere
5. Create it's getter method to access this state.
6. Now retrieve the value with getter & use it anywhere in the app.

Found this method of showing version helpful as we are not dependent on any other library.

**Comment by adityasharma7** [comment]
@shashwatbangar 

Check for any existing libraries, like

https://www.npmjs.com/package/@credenceanalytics/inject-vue-app-version

Also, share any other references that you explored along with this one

**Comment by shashwatbangar** [comment]
> 

This library works perfectly but exploring its code found out it does the same this, taking out the version from package.json and storing in an environment variable so I think we should not install one more package to create one more dependency. What are your views on this sir?

**Comment by shashwatbangar** [comment]
> @shashwatbangar
> 
> Check for any existing libraries, like
> 
> https://www.npmjs.com/package/@credenceanalytics/inject-vue-app-version
> 
> Also, share any other references that you explored along with this one

This library works perfectly but exploring its code found out it does the same this, taking out the version from package.json and storing in an environment variable so I think we should not install one more package to create one more dependency. What are your views on this sir?

**Comment by adityasharma7** [comment]
@shashwatbangar 

Checked the library, it seems it is displaying <Package name> <compile date time> <Patch Branch>

ionic-sdk compiled at Fri Dec 16 2022 16:00:28 GMT+0530 (India Standard Time); Patch Branch = shashwatbangar-#2wn626w

It does miss the package version, though I like the idea of displaying the compile date time, and branch head (helpful when not a release, but the development branch is deployed)

**Comment by shashwatbangar** [comment]
Currently I am trying & testing to slightly modify the code of this package to make it according to our need. If everything works fine, we can think of creating our own npm package to display app version, build DateTime, Branch name & anything else we need.

**Comment by adityasharma7** [comment]
This is done. Closing
