### ISSUE TITLE
Refresh PWA if new version of app is available

### ISSUE THREAD

**Issue by adityasharma7** [hotwax/ionic-sdk#82]
Identify practices of checking for new versions of the app in PWAs and refreshing cache if found

**Comment by adityasharma7** [comment]
https://deanhume.com/displaying-a-new-version-available-progressive-web-app/

**Comment by shashwatbangar** [comment]
References:
https://stackoverflow.com/questions/49739438/when-and-how-does-a-pwa-update-itself
https://web.dev/learn/pwa/update/
https://whatwebcando.today/articles/handling-service-worker-updates/

**Comment by k2maan** [comment]
Reference: https://dev.to/drbragg/handling-service-worker-updates-in-your-vue-pwa-1pip

**Comment by k2maan** [comment]
Merged in Import app. Closing.
