### ISSUE TITLE
Add feature to change facility from Settings page

### ISSUE THREAD

**Issue by shashwatbangar** [hotwax/ionic-sdk#89]
Following apps lacks feature to show facilities on Settings page or show facilities in shopify eCommerce section (Card).
Fix this and update Settings page.

inventory-count
picking
pre-order
bopis
threshold-management

Take following reference

![image](https://user-images.githubusercontent.com/62360781/212671785-953131ff-3ecb-46e1-951a-4c7869702eac.png)

**Comment by disha1202** [comment]
Inventory Count: https://github.com/hotwax/inventory-count/pull/141
Bopis: https://github.com/hotwax/bopis/pull/168
Picking: https://github.com/hotwax/picking/pull/92
Pre-order: NA
Threshold management: NA
